extends: existence
message: "Use an em dash when using characters, not numbers"
link: 'https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#dashes'
nonword: true
level: warning
tokens:
  - \d—\d
