# Should this be a rule we check for or is it understood.
extends: existence
message: "Use first person (such as '%s') sparingly."
link: 'https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#language-and-tone'
ignorecase: true
level: warning
nonword: true
tokens:
  - (?:^|\s)I\s
  - (?:^|\s)I,\s
  - \bI'm\b
  - \bme\b
  - \bmy\b
  - \bmine\b