extends: existence
message: Avoid using geruinds in titles and headings. '%s'
link: "https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#headers"
nonword: true
ignorecase: true
scope: heading
level: error
tokens: 
  - '(?:ing)'


