extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: 'https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#headers'
level: error
scope: heading
match: $sentence