extends: substitution
message: Use gender neutral language when possible. We use “they” to reference unknown third-persons. Consider using '%s' instead of '%s'
link: "https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#inclusivity"
level: error
ignorecase: true
# swap maps tokens in form of bad: good
swap:
    he: they
    she: they
    he/she: they
    he / she: they