extends: existence
message: "Avoid italics '%s'. Instead use bold for emphasis."
link: 'https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#italics'
ignorecase: true
level: error
scope: emphasis
nonword: true
raw:
  - '.+' 
  
# Checks for any characters within an <em> tag.
