extends: substitution
message: Don't abbreviate units of measure except KB, GB and MB. Only abbreviate if you need to save space. Consider using '%s' instead of '%s'
link: 'https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#measurements'
ignorecase: true
level: suggestion
scope: sentence
swap:
  bps : bits per second
  cm : centimeters
  dp : dots per inch
  ft : feet
  Gbps : gigabits per second
  GHz : gigahertz
  Hz : Hertz
  hr : hours
  Kbps : kilobits per second
  kHz : kilohertz
  li : lines
  Mbps : megabits per second
  MBps : megabits per second
  MHz : megahertz
  mm : millimeters
  msec : milliseconds
  ms : milliseconds
  ppi : points per inch
  sec : seconds
  # s : seconds Keeps matching on any . Will need to rethtink these tokens. Might need own rule
  #in. : inches see MeasurementAbbrevetationTwo.yml for these
  #in : inches
