extends: existence
message: "Form a negative number with an en dash, not a hyphen."
link: https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#numbers
nonword: true
level: warning
tokens:
  - '\s-\d+\s'