extends: existence
message: "Spell out all ordinal numbers ('%s') in text."
link: 'https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#numbers'
level: error
nonword: true
tokens:
  - \d+(?:st|th|rd|nd|ly)