extends: existence
message: "Use the Oxford comma in '%s'."
link: 'https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#punctuation'
scope: sentence
level: warning
tokens:
  - '(?:[^,]+,){1,}\s\w+\s(?:and|or)'