extends: existence
message: "Don't use plurals in parentheses such as in '%s'."
link: 'https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#punctuation'
level: error
nonword: true
tokens:
  - '\b\w+\(s\)'