extends: existence
message: Avoid using negative language removing '%s'
link: "https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#language-and-tone"
ignorecase: true
level: suggestion
tokens: 
    - can't
    - don't
    - bad
    - won't
    - Abort
    