extends: existence
message: "Don't use quotation marks. Use bold for empahsis. '%s'."
link: 'https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#punctuation'
ignorecase: true
level: suggestion
nonword: true
scope: sentence
tokens:
  - (?:\"|\')
