extends: existence
message: "Use an en dash in a range of numbers."
link: https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#dashes
nonword: true
level: warning
tokens:
  - '\b\d+\s?[-]\s?\d+\b'