message: "Write shorter sentences (less than 40 words)."
link: "https://github.com/rapid7/metasploit-framework/blob/master/documentation/framework/framework_style_guide.md#sentances"
extends: occurrence
scope: sentence
level: suggestion
max: 40
token: \b(\w+)\b

# This catches an entire sentence and checks if its 40 character long.